[[account]]
name = "Assets:Current Assets:TD Bank:Checking"
short_name = "TD Checking"

[[account]]
name = "Assets:Current Assets:Wallet"
short_name = "Wallet"

[[account]]
name = "Liabilities:Credit Card:TD Visa"
short_name = "TD Visa"
