[[report]]
name = "PY Job Expenses"
chart = "pie"
date_range = "Previous Year"
accounts = [ "Expenses:Job Expenses:*" ]

[[report]]
name = "PQ Expenses"
chart = "pie"
date_range = "Previous Quarter"
accounts = [ "Expenses:*" ]
exclude_account_summary = [ "Job Expenses" ]

[[report]]
name = "PY Expenses"
chart = "pie"
date_range = "Previous Year"
accounts = [ "Expenses:*" ]
exclude_account_summary = [ "Job Expenses", "Taxes" ]

[[report]]
name = "YTD Expenses"
chart = "pie"
date_range = "YTD"
accounts = [ "Expenses:*" ]

[[report]]
name = "YTD My Monthly Savings"
chart = "bar"
date_range = "YTD"
date_freq = "Monthly"
accounts = [ "Income", "Expenses" ]
exclude_account_trans = [ "Income:Wife" ]

    [[report.calculated_account]]
    name = "Savings"

        [[report.calculated_account.account_operation]]
        name = "Income"
        operation = "+"
        
        [[report.calculated_account.account_operation]]
        name = "Expenses"
        operation = "-"

[[report]]
name = "AT Net Worth"
chart = "line"
date_range = "All Time"
date_freq = "Quarterly"
accounts = [ "Assets", "Liabilities" ]

[[report]]
name = "AT Vehicle Depreciation"
chart = "line"
date_range = "All Time"
date_freq = "Quarterly"
accounts = [ "Assets:Fixed Assets", "Expenses:Depreciation" ,"Liabilities:Loans:Auto" ]

[[report]]
name = "AT Vehicle Expenses"
chart = "stackedbar"
date_range = "All Time"
date_freq = "Yearly"
accounts = [ "Expenses:Depreciation", "Expenses:Auto:Gas", "Expenses:Auto:Insurance", "Expenses:Auto:Maintenance" ]

[[report]]
name = "AT Yearly Income"
chart = "bar"
date_range = "All Time"
date_freq = "Yearly"
accounts = [ "Income" ]

